#!/usr/bin/env python3
from pathlib import Path
import re, sys

if len(sys.argv) != 3:
    raise SystemExit('usage: patch.py COMPONENT_ROOT PLUGIN_ROOT')
comp = Path(sys.argv[1]); plug = Path(sys.argv[2])
builder = comp / 'administrator/components/com_decaroforms/tmpl/builder/default.php'
helper = comp / 'administrator/components/com_decaroforms/src/Helper/FormHelper.php'
t = builder.read_text()
h = helper.read_text()

def once(old,new,label):
    global t
    if old not in t:
        raise RuntimeError(f'{label} pattern not found')
    t=t.replace(old,new,1)

def rsub(pattern,repl,label,flags=re.S):
    global t
    t2,n=re.subn(pattern,repl,t,count=1,flags=flags)
    if n!=1:
        raise RuntimeError(f'{label} regex replacements={n}')
    t=t2

# ---- visual language: restore light accordion headers; reserve red for closure area only ----
extra_css = r'''
/* Forms 1.3.2 UX refinements */
.df-section-toggle{background:var(--bs-tertiary-bg,#f7f8fa)!important;color:inherit!important;border:0!important}
.df-section-toggle:hover,.df-section-toggle:focus-visible{background:color-mix(in srgb,var(--bs-tertiary-bg,#f7f8fa) 88%,var(--df) 12%)!important;color:inherit!important}
.df-section-toggle strong,.df-section-chevron{color:inherit!important}
.df-template-row button.is-active{background:var(--bs-body-bg,#fff)!important;color:var(--df)!important;border-color:var(--df)!important;box-shadow:0 0 0 2px color-mix(in srgb,var(--df) 16%,transparent)}
.df-closed-box{grid-column:1/-1;background:var(--df);border-radius:8px;padding:14px}.df-closed-box label{color:#fff}.df-closed-box .df-note{color:#fff;opacity:.9}.df-closed-box input,.df-closed-box select{background:#fff!important;color:#1f2937!important}
.df-switch{display:inline-flex;align-items:center;gap:10px;font-weight:750;cursor:pointer;min-height:42px}.df-switch input{position:absolute;opacity:0;pointer-events:none}.df-switch-ui{position:relative;width:42px;height:24px;border-radius:999px;background:#aeb6c2;transition:.2s}.df-switch-ui:after{content:"";position:absolute;width:18px;height:18px;left:3px;top:3px;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.28);transition:.2s}.df-switch input:checked+.df-switch-ui{background:#0d6efd}.df-switch input:checked+.df-switch-ui:after{transform:translateX(18px)}.df-switch input:focus-visible+.df-switch-ui{outline:3px solid color-mix(in srgb,#0d6efd 28%,transparent);outline-offset:2px}
.df-selected-item .df-selected-config-wrap{display:grid;grid-template-rows:0fr;transition:grid-template-rows .32s ease}.df-selected-item.is-open .df-selected-config-wrap{grid-template-rows:1fr}.df-selected-config-inner{overflow:hidden;min-height:0}.df-field-toggle{border:0;background:transparent;color:inherit;padding:0;text-align:left;cursor:pointer;display:flex;align-items:center;gap:9px;min-width:0}.df-field-toggle-main{min-width:0}.df-field-chevron{transition:transform .25s}.df-selected-item.is-open .df-field-chevron{transform:rotate(180deg)}.df-field-summary{display:flex;gap:6px;flex-wrap:wrap;margin-top:3px}.df-summary-chip{font-size:10px;padding:2px 6px;border:1px solid var(--df-border);border-radius:999px;color:var(--bs-secondary-color,#667085)}
.df-condition-details{grid-column:1/-1;border-top:1px dashed var(--df-border);padding-top:8px}.df-condition-details>summary,.df-field-advanced>summary{cursor:pointer;font-weight:800;list-style:none;display:flex;align-items:center;justify-content:space-between}.df-condition-details>summary::-webkit-details-marker,.df-field-advanced>summary::-webkit-details-marker{display:none}.df-condition-details>summary:after,.df-field-advanced>summary:after{content:'⌄';font-size:12px}.df-condition-details[open]>summary:after,.df-field-advanced[open]>summary:after{transform:rotate(180deg)}.df-condition-body{padding-top:9px}.df-field-advanced{grid-column:1/-1;border-top:1px dashed var(--df-border);padding-top:8px}
.df-layout-visual-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:10px}.df-layout-canvas{display:flex;flex-direction:column;gap:10px}.df-layout-row{min-height:72px;border:1px dashed var(--df-border);border-radius:8px;padding:9px;display:flex;align-items:stretch;gap:8px;background:color-mix(in srgb,var(--bs-tertiary-bg,#f7f8fa) 45%,transparent)}.df-layout-card{position:relative;min-width:120px;max-width:100%;border:1px solid var(--df-border);border-radius:7px;background:var(--bs-body-bg,#fff);padding:10px;display:flex;align-items:center;gap:8px;cursor:grab;box-shadow:0 1px 2px rgba(0,0,0,.04)}.df-layout-card.dragging{opacity:.4}.df-layout-handle{font-weight:900;color:var(--bs-secondary-color,#667085);letter-spacing:-2px}.df-layout-card strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}.df-layout-card select{width:auto;min-width:78px;min-height:32px;border:1px solid var(--df-border);border-radius:5px;background:var(--bs-body-bg,#fff);color:inherit}.df-layout-newrow{min-height:48px;border:1px dashed var(--df-border);border-radius:8px;display:flex;align-items:center;justify-content:center;color:var(--bs-secondary-color,#667085);font-size:12px}.df-layout-row.is-over,.df-layout-newrow.is-over{border-color:var(--df);background:color-mix(in srgb,var(--df) 7%,transparent)}.df-layout-advanced-box{margin-top:12px}.df-layout-empty{padding:22px;border:1px dashed var(--df-border);border-radius:8px;text-align:center;color:var(--bs-secondary-color,#667085)}
.df-library-tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.df-library-tab{border:1px solid var(--df-border);border-radius:999px;min-height:32px;padding:0 10px;background:var(--bs-body-bg,#fff);color:inherit;font-weight:750;font-size:12px;cursor:pointer;display:inline-flex;align-items:center;gap:6px}.df-library-tab.is-active{border-color:var(--df);color:var(--df);box-shadow:0 0 0 2px color-mix(in srgb,var(--df) 12%,transparent)}.df-library-tab-count{font-size:10px;min-width:19px;height:19px;border-radius:999px;background:color-mix(in srgb,var(--df) 10%,transparent);display:inline-flex;align-items:center;justify-content:center}.df-library-tools-v2{display:block;margin-bottom:10px}.df-library-tools-v2 input{width:100%;min-height:42px;border:1px solid var(--df-border);border-radius:6px;background:var(--bs-body-bg,#fff);color:inherit;padding:0 11px}.df-library-items-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.df-library-empty{padding:20px;text-align:center;color:var(--bs-secondary-color,#667085);border:1px dashed var(--df-border);border-radius:7px}
.df-info{border:0;background:transparent;color:#3971c7;font-weight:900;font-size:15px;padding:0 3px;cursor:pointer;vertical-align:middle}.df-info-wrap{position:relative;display:inline-flex;align-items:center}.df-info-bubble{position:absolute;z-index:50;left:50%;top:calc(100% + 7px);transform:translateX(-50%);width:min(320px,76vw);padding:9px 10px;border:1px solid var(--df-border);border-radius:7px;background:var(--bs-body-bg,#fff);color:var(--bs-body-color,#222);box-shadow:0 8px 28px rgba(0,0,0,.16);font-size:12px;font-weight:500;line-height:1.4;display:none}.df-info-wrap.is-open .df-info-bubble{display:block}.df-label-info{display:inline-flex;align-items:center;gap:4px}
.df-email-special-choice{border-style:dashed!important}.df-email-choice[data-special="1"]{background:color-mix(in srgb,var(--bs-tertiary-bg,#f7f8fa) 55%,transparent)}
@media(max-width:800px){.df-library-tabs{flex-wrap:nowrap;overflow-x:auto;padding-bottom:4px}.df-library-tab{flex:0 0 auto}.df-library-items-grid{grid-template-columns:1fr}.df-layout-row{flex-direction:column}.df-layout-card{width:100%!important}.df-selected-config{grid-template-columns:1fr}.df-config-grid{grid-template-columns:1fr}.df-closed-box .df-grid{grid-template-columns:1fr}}
'''
if '</style>' not in t: raise RuntimeError('style close missing')
t=t.replace('</style>',extra_css+'\n</style>',1)

# Switches.
once('<div class="df-field"><label class="df-check"><input type="checkbox" name="enabled" value="1" <?php echo $checked(\'enabled\', true) ? \'checked\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_ENABLED\'); ?></label></div>',
     '<div class="df-field"><label class="df-switch"><input type="checkbox" name="enabled" value="1" <?php echo $checked(\'enabled\', true) ? \'checked\' : \'\'; ?>><span class="df-switch-ui" aria-hidden="true"></span><span><?php echo Text::_(\'COM_DECAROFORMS_ENABLED\'); ?></span></label></div>','enabled switch')
once('<div class="df-field"><label class="df-check"><input type="checkbox" name="show_heading" value="1" <?php echo $checked(\'show_heading\', true) ? \'checked\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_SHOW_HEADING\'); ?></label></div>',
     '<div class="df-field"><label class="df-switch"><input type="checkbox" name="show_heading" value="1" <?php echo $checked(\'show_heading\', true) ? \'checked\' : \'\'; ?>><span class="df-switch-ui" aria-hidden="true"></span><span><?php echo Text::_(\'COM_DECAROFORMS_SHOW_HEADING\'); ?></span></label></div>','heading switch')

# Closure block only gets red emphasis.
old_close='<div class="df-field"><label><?php echo Text::_(\'COM_DECAROFORMS_WHEN_DISABLED\'); ?></label><select name="closed_reason"><option value="closed" <?php echo $val(\'closed_reason\', \'closed\') === \'closed\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_CLOSED_REGISTRATIONS\'); ?></option><option value="limit" <?php echo $val(\'closed_reason\') === \'limit\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_LIMIT_REACHED\'); ?></option><option value="deadline" <?php echo $val(\'closed_reason\') === \'deadline\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_DEADLINE_EXPIRED\'); ?></option><option value="temporary" <?php echo $val(\'closed_reason\') === \'temporary\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_TEMPORARILY_CLOSED\'); ?></option><option value="custom" <?php echo $val(\'closed_reason\') === \'custom\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_CUSTOM_MESSAGE\'); ?></option></select></div>\n        <div class="df-field"><label><?php echo Text::_(\'COM_DECAROFORMS_CLOSED_MESSAGE\'); ?></label><input name="closed_message" value="<?php echo $val(\'closed_message\'); ?>" placeholder="<?php echo htmlspecialchars(Text::_(\'COM_DECAROFORMS_OPTIONAL_CUSTOM_TEXT\'), ENT_QUOTES, \'UTF-8\'); ?>"></div>'
new_close='<div class="df-closed-box"><div class="df-grid"><div class="df-field"><label><?php echo Text::_(\'COM_DECAROFORMS_WHEN_DISABLED\'); ?></label><select name="closed_reason"><option value="closed" <?php echo $val(\'closed_reason\', \'closed\') === \'closed\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_CLOSED_REGISTRATIONS\'); ?></option><option value="limit" <?php echo $val(\'closed_reason\') === \'limit\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_LIMIT_REACHED\'); ?></option><option value="deadline" <?php echo $val(\'closed_reason\') === \'deadline\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_DEADLINE_EXPIRED\'); ?></option><option value="temporary" <?php echo $val(\'closed_reason\') === \'temporary\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_TEMPORARILY_CLOSED\'); ?></option><option value="custom" <?php echo $val(\'closed_reason\') === \'custom\' ? \'selected\' : \'\'; ?>><?php echo Text::_(\'COM_DECAROFORMS_CUSTOM_MESSAGE\'); ?></option></select></div><div class="df-field"><label><?php echo Text::_(\'COM_DECAROFORMS_CLOSED_MESSAGE\'); ?></label><input name="closed_message" value="<?php echo $val(\'closed_message\'); ?>" placeholder="<?php echo htmlspecialchars(Text::_(\'COM_DECAROFORMS_OPTIONAL_CUSTOM_TEXT\'), ENT_QUOTES, \'UTF-8\'); ?>"></div></div></div>'
once(old_close,new_close,'closure block')

# Layout body becomes a visual drag/drop canvas; keep numeric controls under Advanced.
layout_old='''        <div class="df-grid"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_LAYOUT_COLUMNS'); ?></label><select id="df-layout-columns"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-layout-mobile-stack"> <?php echo Text::_('COM_DECAROFORMS_LAYOUT_MOBILE_STACK'); ?></label></div></div>
        <div class="df-layout-widths" id="df-layout-widths"></div>
        <div class="df-spread" style="margin-top:8px"><span class="df-layout-total" id="df-layout-total"></span><button class="df-btn df-small" type="button" id="df-layout-apply"><?php echo Text::_('COM_DECAROFORMS_LAYOUT_APPLY_FIELDS'); ?></button></div>
        <div class="df-presets"><button class="df-preset" type="button" data-layout-preset="100">100%</button><button class="df-preset" type="button" data-layout-preset="50,50">50 / 50</button><button class="df-preset" type="button" data-layout-preset="30,70">30 / 70</button><button class="df-preset" type="button" data-layout-preset="70,30">70 / 30</button><button class="df-preset" type="button" data-layout-preset="33,33,34">33 / 33 / 34</button><button class="df-preset" type="button" data-layout-preset="25,25,25,25">25 / 25 / 25 / 25</button></div>
        <p class="df-note"><?php echo Text::_('COM_DECAROFORMS_LAYOUT_NOTE'); ?></p>'''
layout_new='''        <div class="df-layout-visual-head"><div><strong>Layout visuale</strong><div class="df-note">Trascina i campi tra le righe e scegli rapidamente la larghezza.</div></div><label class="df-switch"><input type="checkbox" id="df-layout-mobile-stack"><span class="df-switch-ui" aria-hidden="true"></span><span><?php echo Text::_('COM_DECAROFORMS_LAYOUT_MOBILE_STACK'); ?></span></label></div>
        <div class="df-layout-canvas" id="df-layout-canvas"></div>
        <div class="df-layout-newrow" id="df-layout-newrow">Trascina qui un campo per creare una nuova riga</div>
        <details class="df-layout-advanced-box"><summary><strong>Impostazioni layout avanzate</strong></summary><div style="padding-top:10px"><div class="df-grid"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_LAYOUT_COLUMNS'); ?></label><select id="df-layout-columns"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div><div class="df-field"><span class="df-layout-total" id="df-layout-total"></span></div></div><div class="df-layout-widths" id="df-layout-widths"></div><div class="df-spread" style="margin-top:8px"><div class="df-presets"><button class="df-preset" type="button" data-layout-preset="100">100%</button><button class="df-preset" type="button" data-layout-preset="50,50">50 / 50</button><button class="df-preset" type="button" data-layout-preset="30,70">30 / 70</button><button class="df-preset" type="button" data-layout-preset="70,30">70 / 30</button><button class="df-preset" type="button" data-layout-preset="33,33,34">33 / 33 / 34</button><button class="df-preset" type="button" data-layout-preset="25,25,25,25">25 / 25 / 25 / 25</button></div><button class="df-btn df-small" type="button" id="df-layout-apply"><?php echo Text::_('COM_DECAROFORMS_LAYOUT_APPLY_FIELDS'); ?></button></div></div></details>'''
once(layout_old,layout_new,'layout markup')

# Library: categories as compact pills above, search below.
lib_old='<div class="df-section-body-wrap"><div class="df-section-body-inner"><div class="df-section-body"><div class="df-library-tools"><input type="search" id="df-library-search" placeholder="<?php echo htmlspecialchars(Text::_(\'COM_DECAROFORMS_SEARCH_FIELD\'), ENT_QUOTES, \'UTF-8\'); ?>"><select id="df-library-filter"></select></div><div class="df-library" id="df-library"></div></div></div></div>'
lib_new='<div class="df-section-body-wrap"><div class="df-section-body-inner"><div class="df-section-body"><div class="df-library-tabs" id="df-library-tabs"></div><div class="df-library-tools-v2"><input type="search" id="df-library-search" placeholder="<?php echo htmlspecialchars(Text::_(\'COM_DECAROFORMS_SEARCH_FIELD\'), ENT_QUOTES, \'UTF-8\'); ?>"><select id="df-library-filter" hidden></select></div><div class="df-library" id="df-library"></div></div></div></div>'
once(lib_old,lib_new,'library markup')

# Validation wording + clickable info explanations.
val_old='''        <div class="df-subbox"><h4><?php echo Text::_('COM_DECAROFORMS_VALIDATION'); ?></h4><div class="df-security-grid"><div class="df-field"><label class="df-check"><input type="checkbox" id="df-validation-ajax"> <?php echo Text::_('COM_DECAROFORMS_AJAX_VALIDATION'); ?></label></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-validation-scroll"> <?php echo Text::_('COM_DECAROFORMS_SCROLL_ERROR'); ?></label></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_REQUIRED_MARKER'); ?></label><input id="df-required-marker" maxlength="8"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_ERROR_MESSAGE'); ?></label><input id="df-error-message"></div></div></div>
        <div class="df-subbox"><h4><?php echo Text::_('COM_DECAROFORMS_CONFIRMATION'); ?></h4><div class="df-security-grid"><div class="df-field"><label class="df-check"><input type="checkbox" id="df-confirm-enabled"> <?php echo Text::_('COM_DECAROFORMS_SHOW_CONFIRMATION'); ?></label></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_CONFIRM_POSITION'); ?></label><select id="df-confirm-position"><option value="below"><?php echo Text::_('COM_DECAROFORMS_CONFIRM_BELOW'); ?></option><option value="replace"><?php echo Text::_('COM_DECAROFORMS_CONFIRM_REPLACE'); ?></option><option value="modal"><?php echo Text::_('COM_DECAROFORMS_CONFIRM_MODAL'); ?></option></select></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-confirm-scroll"> <?php echo Text::_('COM_DECAROFORMS_SCROLL_CONFIRM'); ?></label></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-confirm-continue"> <?php echo Text::_('COM_DECAROFORMS_SHOW_CONTINUE'); ?></label></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_CONTINUE_LABEL'); ?></label><input id="df-confirm-continue-label"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_CONTINUE_URL'); ?></label><input id="df-confirm-continue-url" placeholder="https://..."></div></div></div>
        <div class="df-subbox"><h4><?php echo Text::_('COM_DECAROFORMS_SECURITY'); ?></h4><div class="df-security-grid"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_MIN_SECONDS'); ?></label><input type="number" id="df-min-seconds" min="0" max="60"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_RATE_SECONDS'); ?></label><input type="number" id="df-rate-seconds" min="0" max="3600"></div></div><p class="df-note"><?php echo Text::_('COM_DECAROFORMS_SECURITY_NOTE'); ?></p></div>'''
val_new='''        <div class="df-subbox"><h4>Controllo dei campi</h4><div class="df-security-grid"><div class="df-field"><label class="df-check"><input type="checkbox" id="df-validation-ajax"><span>Controlla i campi prima dell’invio</span><span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Verifica subito che i campi obbligatori e i valori inseriti siano corretti prima dell’invio.</span></span></label></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-validation-scroll"><span>Vai al primo campo con errore</span><span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Se c’è un errore, porta automaticamente l’utente al primo campo da correggere.</span></span></label></div><div class="df-field"><label class="df-label-info">Simbolo per i campi obbligatori <span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">È il simbolo mostrato accanto ai campi obbligatori. Il valore predefinito è *.</span></span></label><input id="df-required-marker" maxlength="8"></div><div class="df-field"><label class="df-label-info">Messaggio generale in caso di errore <span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Messaggio mostrato quando uno o più campi non sono compilati correttamente.</span></span></label><input id="df-error-message"></div></div></div>
        <div class="df-subbox"><h4>Conferma dopo l’invio</h4><div class="df-security-grid"><div class="df-field"><label class="df-check"><input type="checkbox" id="df-confirm-enabled"><span>Mostra messaggio di conferma</span></label></div><div class="df-field"><label class="df-label-info">Dove mostrare il messaggio <span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Scegli se mostrarlo sotto Invia, al posto del modulo oppure in una finestra.</span></span></label><select id="df-confirm-position"><option value="below"><?php echo Text::_('COM_DECAROFORMS_CONFIRM_BELOW'); ?></option><option value="replace"><?php echo Text::_('COM_DECAROFORMS_CONFIRM_REPLACE'); ?></option><option value="modal"><?php echo Text::_('COM_DECAROFORMS_CONFIRM_MODAL'); ?></option></select></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-confirm-scroll"><span>Vai automaticamente al messaggio</span></label></div><div class="df-field"><label class="df-check"><input type="checkbox" id="df-confirm-continue"><span>Mostra pulsante Continua</span></label></div><div class="df-field"><label>Testo del pulsante Continua</label><input id="df-confirm-continue-label"></div><div class="df-field"><label>Pagina da aprire dopo Continua</label><input id="df-confirm-continue-url" placeholder="https://..."></div></div></div>
        <div class="df-subbox"><h4>Protezione dagli invii automatici</h4><div class="df-security-grid"><div class="df-field"><label class="df-label-info">Tempo minimo per compilare il modulo <span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Blocca gli invii completati in modo anormalmente veloce, tipici dei bot.</span></span></label><input type="number" id="df-min-seconds" min="0" max="60"></div><div class="df-field"><label class="df-label-info">Attesa minima tra due invii <span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Impedisce invii ripetuti a distanza di pochi secondi.</span></span></label><input type="number" id="df-rate-seconds" min="0" max="3600"></div></div><p class="df-note">Le protezioni di sicurezza principali sono sempre attive. <span class="df-info-wrap"><button class="df-info" type="button" aria-label="Informazioni">ⓘ</button><span class="df-info-bubble">Comprendono controllo della richiesta, campo anti-bot invisibile e verifica lato server.</span></span></p></div>'''
once(val_old,val_new,'validation markup')

# Exactly seven default visual templates + Personalizzato + HTML + AI.
t=t.replace("['receipt','<?php echo addslashes(Text::_('COM_DECAROFORMS_TEMPLATE_RECEIPT')); ?>'],",'',1)
t=t.replace("['chatgpt','ChatGPT']","['chatgpt','AI']",1)

# Always source library directly from helper (keep 1.3.1 fix).
t=t.replace("const library=<?php echo json_encode($this->library, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;","const library=<?php echo json_encode(FormHelper::fieldLibrary(), JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;",1)

# Add open state for field accordions and open newly added field.
once("selected=selected.map(defaultFieldConfig);\nfunction add(item){const x=defaultFieldConfig(clone(item));x.key=uniqueKey(x.key);x.options=Array.isArray(x.options)?x.options:[];selected.push(x);renderSelected();renderColumns();renderTokens();renderUserEmailFields();}",
     "selected=selected.map(defaultFieldConfig);\nconst openFieldKeys=new Set(selected.slice(0,1).map(x=>x.key));\nfunction add(item){const x=defaultFieldConfig(clone(item));x.key=uniqueKey(x.key);x.options=Array.isArray(x.options)?x.options:[];selected.push(x);openFieldKeys.add(x.key);renderSelected();renderLayoutCanvas();renderColumns();renderTokens();renderUserEmailFields();sync();}", 'add/open state')

# Library renderer with compact category tabs and global search.
rsub(r"function renderLibrary\(\)\{.*?function fieldSelectOptions\(current=''\)", r'''let activeLibraryCategory='personal';
function renderLibrary(){
 const tabs=document.getElementById('df-library-tabs');
 const q=(search.value||'').trim().toLowerCase();
 const counts=Object.fromEntries(categoryOrder.map(c=>[c,library.filter(x=>x.category===c).length]));
 tabs.innerHTML=`<button type="button" class="df-library-tab ${activeLibraryCategory==='all'?'is-active':''}" data-libcat="all">Tutti <span class="df-library-tab-count">${library.length}</span></button>`+categoryOrder.map(c=>`<button type="button" class="df-library-tab ${activeLibraryCategory===c?'is-active':''}" data-libcat="${c}">${esc(tr.cats[c]||c)} <span class="df-library-tab-count">${counts[c]||0}</span></button>`).join('');
 tabs.querySelectorAll('[data-libcat]').forEach(b=>b.onclick=()=>{activeLibraryCategory=b.dataset.libcat;renderLibrary();});
 const items=library.filter(x=>(q||activeLibraryCategory==='all'||x.category===activeLibraryCategory)&&(!q||`${x.label} ${x.key} ${x.type} ${tr.cats[x.category]||''}`.toLowerCase().includes(q)));
 lib.innerHTML='';
 if(!items.length){lib.innerHTML='<div class="df-library-empty">Nessun campo trovato.</div>';return;}
 const grid=document.createElement('div');grid.className='df-library-items-grid';
 items.forEach(x=>{const d=document.createElement('div');d.className='df-lib-item';d.innerHTML=`<div><strong>${esc(x.label)}</strong><small>${esc(tr.cats[x.category]||x.category)} · ${esc(tr.types[x.type]||x.type)}</small></div><button class="df-add" type="button">${esc(tr.add)}</button>`;d.querySelector('button').onclick=()=>add(x);grid.appendChild(d);});lib.appendChild(grid);
}
filter.innerHTML='';filter.hidden=true;search.addEventListener('input',renderLibrary);renderLibrary();

function fieldSelectOptions(current='')''','library renderer')

# Selected fields: outer accordion per field + nested conditions accordion + manual layout under Advanced.
rsub(r"function renderConditions\(x,i\)\{.*?\n\n// Layout\.", r'''function renderConditions(x,i){const c=x.config||{},rules=Array.isArray(c.conditions)?c.conditions:[];const rows=rules.map((r,ri)=>`<div class="df-condition-row"><select data-cond-field="${ri}"><option value="">—</option>${fieldSelectOptions(r.field||'')}</select><select data-cond-op="${ri}">${[['eq','='],['neq','≠'],['contains','contiene'],['not_contains','non contiene'],['empty','vuoto'],['not_empty','non vuoto'],['gt','>'],['lt','<'],['checked','selezionato'],['not_checked','non selezionato']].map(([v,l])=>`<option value="${v}" ${r.operator===v?'selected':''}>${l}</option>`).join('')}</select><input data-cond-value="${ri}" value="${esc(r.value||'')}" placeholder="Valore"><button type="button" data-cond-remove="${ri}">×</button></div>`).join('');return `<details class="df-condition-details"><summary>${esc(tr.conditions)} <span class="df-note">${rules.length?rules.length+' regola'+(rules.length===1?'':'e'):''}</span></summary><div class="df-condition-body"><div class="df-spread"><span class="df-note">Mostra, nascondi o rendi obbligatorio questo campo in base ad altri valori.</span><button class="df-btn df-small" type="button" data-add-condition>+ ${esc(tr.addCondition)}</button></div><div class="df-config-grid" style="margin-top:8px"><div><label>Azione</label><select data-cfg="condition_action"><option value="show" ${c.condition_action==='show'?'selected':''}>Mostra</option><option value="hide" ${c.condition_action==='hide'?'selected':''}>Nascondi</option><option value="require" ${c.condition_action==='require'?'selected':''}>Rendi obbligatorio</option><option value="disable" ${c.condition_action==='disable'?'selected':''}>Disabilita</option></select></div><div><label>Come applicare le regole</label><select data-cfg="condition_logic"><option value="all" ${c.condition_logic!=='any'?'selected':''}>${esc(tr.all)}</option><option value="any" ${c.condition_logic==='any'?'selected':''}>${esc(tr.any)}</option></select></div></div><div class="df-condition-list">${rows||`<div class="df-note">Nessuna condizione configurata.</div>`}</div></div></details>`;}
function renderSelected(){sel.innerHTML='';if(!selected.length){sel.innerHTML=`<div class="df-selected-empty">${esc(tr.empty)}</div>`;sync();renderLayoutCanvas();return;}selected.forEach((x,i)=>{defaultFieldConfig(x);const d=document.createElement('div');d.className='df-selected-item'+(openFieldKeys.has(x.key)?' is-open':'');const req=x.required?'<span class="df-summary-chip">Obbligatorio</span>':'';d.innerHTML=`<div class="df-selected-top"><button type="button" class="df-field-toggle" data-field-toggle><span class="df-field-chevron">⌄</span><span class="df-field-toggle-main"><strong>${i+1}. ${esc(x.label)}</strong><span class="df-field-summary"><span class="df-summary-chip">${esc(tr.types[x.type]||x.type)}</span>${req}<span class="df-summary-chip">${esc(x.config.layout.width||100)}%</span></span></span></button><div class="df-mini-actions"><button type="button" data-act="up" title="${esc(tr.moveUp)}">↑</button><button type="button" data-act="down" title="${esc(tr.moveDown)}">↓</button><button type="button" data-act="remove" title="${esc(tr.remove)}">×</button></div></div><div class="df-selected-config-wrap"><div class="df-selected-config-inner"><div class="df-selected-config"><div><label>${esc(tr.label)}</label><input data-k="label" value="${esc(x.label)}"></div><div><label>${esc(tr.key)}</label><input data-k="key" value="${esc(x.key)}"></div><div><label>${esc(tr.type)}</label><select data-k="type">${types.map(t=>`<option value="${t}" ${x.type===t?'selected':''}>${esc(tr.types[t]||t)}</option>`).join('')}</select></div><div><label>${esc(tr.placeholder)}</label><input data-k="placeholder" value="${esc(x.placeholder||'')}"></div><div><label>${esc(tr.default)}</label><input data-k="default" value="${esc(x.default||'')}"></div><div><label>${esc(tr.help)}</label><input data-k="help" value="${esc(x.help||'')}"></div><div class="full df-required"><input type="checkbox" data-k-check="required" ${x.required?'checked':''}><label>${esc(tr.required)}</label></div>${configHtml(x)}<details class="df-field-advanced"><summary>Layout manuale avanzato</summary><div class="df-config-grid" style="margin-top:8px"><div><label>Riga</label><input type="number" min="1" data-cfg="layout.row" value="${esc(x.config.layout.row||1)}"></div><div><label>Colonna</label><input type="number" min="1" max="20" data-cfg="layout.col" value="${esc(x.config.layout.col||1)}"></div><div><label>Larghezza %</label><input type="number" min="10" max="100" data-cfg="layout.width" value="${esc(x.config.layout.width||100)}"></div></div></details>${renderConditions(x,i)}</div></div></div>`;
 d.querySelector('[data-field-toggle]').onclick=()=>{openFieldKeys.has(x.key)?openFieldKeys.delete(x.key):openFieldKeys.add(x.key);d.classList.toggle('is-open',openFieldKeys.has(x.key));};
 d.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',()=>{const k=el.dataset.k;if(k==='options')x.options=el.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);else{x[k]=el.value;if(k==='key'&&el.value!==x.key){openFieldKeys.delete(x.key);openFieldKeys.add(el.value);}}sync();if(k==='label'||k==='key'){renderColumns();renderTokens();renderUserEmailFields();renderAdditional();renderLayoutCanvas();}if(k==='type'){renderSelected();renderColumns();renderUserEmailFields();}}));
 d.querySelectorAll('[data-k-check]').forEach(el=>el.addEventListener('change',()=>{x[el.dataset.kCheck]=el.checked;sync();renderSelected();}));
 d.querySelectorAll('[data-cfg]').forEach(el=>{const ev=el.tagName==='SELECT'?'change':'input';el.addEventListener(ev,()=>{setDeep(x.config,el.dataset.cfg,el.type==='number'?Number(el.value):el.value);sync();if(el.dataset.cfg.startsWith('layout.'))renderLayoutCanvas();});});
 d.querySelectorAll('[data-cfg-check]').forEach(el=>el.addEventListener('change',()=>{setDeep(x.config,el.dataset.cfgCheck,el.checked);sync();}));
 d.querySelector('[data-act="up"]').onclick=()=>{if(i>0){[selected[i-1],selected[i]]=[selected[i],selected[i-1]];renderSelected();renderLayoutCanvas();}};d.querySelector('[data-act="down"]').onclick=()=>{if(i<selected.length-1){[selected[i+1],selected[i]]=[selected[i],selected[i+1]];renderSelected();renderLayoutCanvas();}};d.querySelector('[data-act="remove"]').onclick=()=>{openFieldKeys.delete(x.key);selected.splice(i,1);normalizeLayoutRows();renderSelected();renderLayoutCanvas();renderColumns();renderTokens();renderUserEmailFields();renderAdditional();};
 d.querySelector('[data-add-condition]')?.addEventListener('click',e=>{e.preventDefault();x.config.conditions.push({field:'',operator:'eq',value:''});renderSelected();setTimeout(()=>{const items=sel.querySelectorAll('.df-selected-item');items[i]?.querySelector('.df-condition-details')?.setAttribute('open','');},0);});d.querySelectorAll('[data-cond-field]').forEach(el=>el.addEventListener('change',()=>{x.config.conditions[Number(el.dataset.condField)].field=el.value;sync();}));d.querySelectorAll('[data-cond-op]').forEach(el=>el.addEventListener('change',()=>{x.config.conditions[Number(el.dataset.condOp)].operator=el.value;sync();}));d.querySelectorAll('[data-cond-value]').forEach(el=>el.addEventListener('input',()=>{x.config.conditions[Number(el.dataset.condValue)].value=el.value;sync();}));d.querySelectorAll('[data-cond-remove]').forEach(el=>el.addEventListener('click',()=>{x.config.conditions.splice(Number(el.dataset.condRemove),1);renderSelected();}));sel.appendChild(d);});sync();renderLayoutCanvas();}

// Layout.''','selected accordions')

# Visual drag/drop layout engine.
rsub(r"// Layout\.\n.*?\n// Statuses and columns\.", r'''// Layout.
const layoutColumns=document.getElementById('df-layout-columns'),layoutWidths=document.getElementById('df-layout-widths'),layoutTotal=document.getElementById('df-layout-total'),mobileStack=document.getElementById('df-layout-mobile-stack'),layoutCanvas=document.getElementById('df-layout-canvas'),layoutNewRow=document.getElementById('df-layout-newrow');
let draggedFieldIndex=null;
function normalizeLayoutRows(){const rows=[...new Set(selected.map(f=>Number(f.config?.layout?.row||1)))].sort((a,b)=>a-b);const map=new Map(rows.map((r,i)=>[r,i+1]));selected.forEach(f=>{defaultFieldConfig(f);f.config.layout.row=map.get(Number(f.config.layout.row||1))||1;});for(const row of [...new Set(selected.map(f=>f.config.layout.row))])selected.filter(f=>f.config.layout.row===row).sort((a,b)=>(a.config.layout.col||1)-(b.config.layout.col||1)).forEach((f,i)=>f.config.layout.col=i+1);}
function widthChoices(current){const vals=[25,30,33,40,50,60,66,70,75,100];if(!vals.includes(Number(current)))vals.push(Number(current)||100);return vals.sort((a,b)=>a-b).map(v=>`<option value="${v}" ${Number(current)===v?'selected':''}>${v}%</option>`).join('');}
function moveFieldToRow(index,row){if(index==null||!selected[index])return;defaultFieldConfig(selected[index]);selected[index].config.layout.row=row;normalizeLayoutRows();sync();renderLayoutCanvas();renderSelected();}
function renderLayoutCanvas(){if(!layoutCanvas)return;normalizeLayoutRows();layoutCanvas.innerHTML='';if(!selected.length){layoutCanvas.innerHTML='<div class="df-layout-empty">Aggiungi prima i campi dalla Libreria o da un Modello rapido.</div>';return;}const rows=[...new Set(selected.map(f=>Number(f.config.layout.row||1)))].sort((a,b)=>a-b);rows.forEach(rowNo=>{const row=document.createElement('div');row.className='df-layout-row';row.dataset.row=String(rowNo);selected.map((f,i)=>[f,i]).filter(([f])=>Number(f.config.layout.row||1)===rowNo).sort(([a],[b])=>(a.config.layout.col||1)-(b.config.layout.col||1)).forEach(([f,i])=>{const card=document.createElement('div');card.className='df-layout-card';card.draggable=true;card.style.width=`${Math.max(10,Math.min(100,Number(f.config.layout.width||100)))}%`;card.innerHTML=`<span class="df-layout-handle" title="Trascina">⋮⋮</span><strong>${esc(f.label)}</strong><select aria-label="Larghezza campo">${widthChoices(f.config.layout.width||100)}</select>`;card.addEventListener('dragstart',()=>{draggedFieldIndex=i;card.classList.add('dragging');});card.addEventListener('dragend',()=>{draggedFieldIndex=null;card.classList.remove('dragging');document.querySelectorAll('.is-over').forEach(x=>x.classList.remove('is-over'));});card.querySelector('select').onchange=e=>{f.config.layout.width=Number(e.target.value);sync();renderLayoutCanvas();renderSelected();};row.appendChild(card);});row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('is-over');});row.addEventListener('dragleave',()=>row.classList.remove('is-over'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('is-over');moveFieldToRow(draggedFieldIndex,rowNo);});layoutCanvas.appendChild(row);});sync();}
layoutNewRow?.addEventListener('dragover',e=>{e.preventDefault();layoutNewRow.classList.add('is-over');});layoutNewRow?.addEventListener('dragleave',()=>layoutNewRow.classList.remove('is-over'));layoutNewRow?.addEventListener('drop',e=>{e.preventDefault();layoutNewRow.classList.remove('is-over');const max=Math.max(0,...selected.map(f=>Number(f.config?.layout?.row||1)));moveFieldToRow(draggedFieldIndex,max+1);});
function renderLayout(){let n=Math.max(1,Math.min(4,Number(builderConfig.layout.columns||1)));builderConfig.layout.columns=n;layoutColumns.value=String(n);mobileStack.checked=builderConfig.layout.mobile_stack!==false;let widths=Array.isArray(builderConfig.layout.widths)?builderConfig.layout.widths.slice(0,n).map(Number):[];while(widths.length<n)widths.push(Math.floor(100/n));if(n===1)widths=[100];builderConfig.layout.widths=widths;layoutWidths.innerHTML='';for(let i=0;i<4;i++){const w=document.createElement('div');w.className='df-field';if(i>=n)w.hidden=true;w.innerHTML=`<label>Colonna ${i+1}</label><input type="number" min="0" max="100" data-width="${i}" value="${esc(widths[i]??0)}">`;w.querySelector('input').addEventListener('input',e=>{builderConfig.layout.widths[i]=Number(e.target.value||0);renderLayoutTotal();sync();});layoutWidths.appendChild(w);}renderLayoutTotal();renderLayoutCanvas();sync();}
function renderLayoutTotal(){const total=(builderConfig.layout.widths||[]).slice(0,builderConfig.layout.columns).reduce((a,b)=>a+Number(b||0),0);layoutTotal.textContent=`Totale: ${total}%`;layoutTotal.classList.toggle('is-ok',total===100);layoutTotal.classList.toggle('is-error',total!==100);}
layoutColumns.addEventListener('change',()=>{builderConfig.layout.columns=Number(layoutColumns.value);builderConfig.layout.widths=Array.from({length:builderConfig.layout.columns},(_,i)=>builderConfig.layout.widths?.[i]??Math.floor(100/builderConfig.layout.columns));if(builderConfig.layout.columns===1)builderConfig.layout.widths=[100];renderLayout();});mobileStack.addEventListener('change',()=>{builderConfig.layout.mobile_stack=mobileStack.checked;sync();});document.querySelectorAll('[data-layout-preset]').forEach(b=>b.addEventListener('click',()=>{const w=b.dataset.layoutPreset.split(',').map(Number);builderConfig.layout.columns=w.length;builderConfig.layout.widths=w;renderLayout();}));document.getElementById('df-layout-apply').addEventListener('click',e=>{const widths=builderConfig.layout.widths.slice(0,builderConfig.layout.columns);selected.forEach((f,i)=>{defaultFieldConfig(f);const col=(i%builderConfig.layout.columns)+1,row=Math.floor(i/builderConfig.layout.columns)+1;f.config.layout={row,col,width:widths[col-1]||100};});renderSelected();renderLayoutCanvas();sync();const btn=e.currentTarget,old=btn.textContent;btn.textContent=selected.length?`✓ Applicato a ${selected.length} camp${selected.length===1?'o':'i'}`:'Nessun campo selezionato';setTimeout(()=>btn.textContent=old,1600);});

// Statuses and columns.''','visual layout')

# Quick templates: make the core operation isolated and reliable; open Selected fields after success.
old_quick="""// Quick templates.
const libByKey=()=>Object.fromEntries(library.map(x=>[x.key,x]));
const formTemplates={contact:['first_name','last_name','email','phone','subject','message','privacy_consent'],registration:['first_name','last_name','birth_date','email','phone','address','postcode','city','privacy_consent'],event:['first_name','last_name','email','event_date','participants','notes','privacy_consent'],membership:['first_name','last_name','birth_date','email','phone','address','postcode','city','member_number','privacy_consent'],reservation:['first_name','last_name','email','phone','event_date','participants','notes'],blank:[]};
function openBuilderSection(index,scroll=false){const sections=[...document.querySelectorAll('[data-accordion]')],section=sections[index];if(!section)return;if(window.matchMedia('(max-width:800px)').matches){sections.forEach((x,i)=>{if(i!==index){x.classList.remove('is-open');x.querySelector('.df-section-toggle')?.setAttribute('aria-expanded','false');}});}section.classList.add('is-open');section.querySelector('.df-section-toggle')?.setAttribute('aria-expanded','true');if(scroll)setTimeout(()=>section.scrollIntoView({behavior:'smooth',block:'start'}),80);}
document.querySelectorAll('[data-form-template]').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.formTemplate,map=libByKey();if(name==='blank'){selected=[];}else{selected=(formTemplates[name]||[]).map(k=>map[k]?defaultFieldConfig(clone(map[k])):null).filter(Boolean);selected.forEach((f,i)=>{f.key=String(f.key||('field_'+(i+1)));f.config.layout={row:i+1,col:1,width:100};});}document.querySelectorAll('[data-form-template]').forEach(x=>x.classList.toggle('is-active',x===b));renderSelected();renderColumns();renderTokens();renderUserEmailFields();renderAdditional();sync();const quickSection=[...document.querySelectorAll('[data-accordion]')][1];quickSection?.classList.remove('is-open');quickSection?.querySelector('.df-section-toggle')?.setAttribute('aria-expanded','false');openBuilderSection(2,true);}));"""
new_quick="""// Quick templates.
const libByKey=()=>Object.fromEntries(library.map(x=>[x.key,x]));
const formTemplates={contact:['first_name','last_name','email','phone','subject','message','privacy_consent'],registration:['first_name','last_name','birth_date','email','phone','address','postcode','city','privacy_consent'],event:['first_name','last_name','email','event_date','participants','notes','privacy_consent'],membership:['first_name','last_name','birth_date','email','phone','address','postcode','city','member_number','privacy_consent'],reservation:['first_name','last_name','email','phone','event_date','participants','notes'],blank:[]};
function openBuilderSection(index,scroll=false){const sections=[...document.querySelectorAll('[data-accordion]')],section=sections[index];if(!section)return;if(window.matchMedia('(max-width:800px)').matches){sections.forEach((x,i)=>{if(i!==index){x.classList.remove('is-open');x.querySelector('.df-section-toggle')?.setAttribute('aria-expanded','false');}});}section.classList.add('is-open');section.querySelector('.df-section-toggle')?.setAttribute('aria-expanded','true');if(scroll)setTimeout(()=>section.scrollIntoView({behavior:'smooth',block:'start'}),80);}
document.querySelectorAll('[data-form-template]').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.formTemplate,map=libByKey();try{if(name==='blank'){selected=[];openFieldKeys.clear();}else{const wanted=formTemplates[name]||[];const next=[];wanted.forEach(k=>{if(!map[k])return;const f=defaultFieldConfig(clone(map[k]));f.key=String(f.key||k);f.options=Array.isArray(f.options)?f.options:[];next.push(f);});selected=next;selected.forEach((f,i)=>{f.config.layout={row:i+1,col:1,width:100};});openFieldKeys.clear();if(selected[0])openFieldKeys.add(selected[0].key);}sync();renderSelected();renderLayoutCanvas();renderColumns();renderTokens();renderUserEmailFields();renderAdditional();document.querySelectorAll('[data-form-template]').forEach(x=>x.classList.toggle('is-active',x===b));const quick=[...document.querySelectorAll('[data-accordion]')][1];quick?.classList.remove('is-open');quick?.querySelector('.df-section-toggle')?.setAttribute('aria-expanded','false');openBuilderSection(2,true);}catch(err){console.error('Forms quick template error',err);alert('Impossibile caricare il modello rapido. Ricarica la pagina e riprova.');}}));"""
if old_quick not in t:
    # fallback for slightly formatted 1.3.1 block
    pat=r"// Quick templates\.\nconst libByKey=.*?openBuilderSection\(2,true\);\n?\}\)\);"
    t2,n=re.subn(pat,new_quick,t,count=1,flags=re.S)
    if n!=1: raise RuntimeError('quick template block not found')
    t=t2
else:t=t.replace(old_quick,new_quick,1)

# Info popovers: click/tap, close outside or Escape.
insert="""
document.addEventListener('click',e=>{const btn=e.target.closest('.df-info');if(btn){e.preventDefault();e.stopPropagation();const wrap=btn.closest('.df-info-wrap');document.querySelectorAll('.df-info-wrap.is-open').forEach(x=>{if(x!==wrap)x.classList.remove('is-open');});wrap?.classList.toggle('is-open');return;}if(!e.target.closest('.df-info-wrap'))document.querySelectorAll('.df-info-wrap.is-open').forEach(x=>x.classList.remove('is-open'));});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.df-info-wrap.is-open').forEach(x=>x.classList.remove('is-open'));});
"""
anchor="// Email configuration and previews."
if anchor not in t: raise RuntimeError('info popover anchor missing')
t=t.replace(anchor,insert+'\n'+anchor,1)

# Seven defaults + 3 advanced cards: mark special cards and normalize old receipt selection.
t=t.replace("const templateDefs=[['standard','Standard'],['minimal','Minimal'],['institutional'", "const templateDefs=[['standard','Standard'],['minimal','Minimal'],['institutional'",1)
t=t.replace("function renderEmailPickers(){document.querySelectorAll('[data-email-picker]').forEach(box=>{const audience=box.dataset.emailPicker,config=emailConfig[audience];box.innerHTML='';templateDefs.forEach(([key,label])=>{const card=document.createElement('div');card.className='df-email-choice'+((config.template||'standard')===key?' is-active':'');", "function renderEmailPickers(){document.querySelectorAll('[data-email-picker]').forEach(box=>{const audience=box.dataset.emailPicker,config=emailConfig[audience];if(config.template==='receipt')config.template='standard';box.innerHTML='';templateDefs.forEach(([key,label])=>{const card=document.createElement('div');const special=['custom','html','chatgpt'].includes(key);card.className='df-email-choice'+((config.template||'standard')===key?' is-active':'');card.dataset.special=special?'1':'0';",1)

# Add payment fields to library.
payment_line="            ['key'=>'payment','type'=>'payment','category'=>'payment','label'=>Text::_('COM_DECAROFORMS_PAYMENT'),'placeholder'=>'','required'=>false,'config'=>['method'=>'bank','iban'=>'','holder'=>'','amount'=>'','cause'=>'{last_name} {first_name} - {riferimento}']],\n"
if payment_line not in h: raise RuntimeError('payment library line missing')
payment_fields=payment_line+"            ['key'=>'payment_method','type'=>'select','category'=>'payment','label'=>Text::_('COM_DECAROFORMS_FIELD_PAYMENT_METHOD'),'placeholder'=>'','required'=>false,'options'=>['Bonifico bancario','Carta — '.Text::_('COM_DECAROFORMS_COMING_SOON'),'PayPal — '.Text::_('COM_DECAROFORMS_COMING_SOON')]],\n            ['key'=>'iban','type'=>'text','category'=>'payment','label'=>'IBAN','placeholder'=>'IT00 A000 0000 0000 0000 0000 000','required'=>false,'config'=>['uppercase'=>true]],\n            ['key'=>'account_holder','type'=>'text','category'=>'payment','label'=>Text::_('COM_DECAROFORMS_ACCOUNT_HOLDER'),'placeholder'=>'','required'=>false],\n            ['key'=>'payment_amount','type'=>'text','category'=>'payment','label'=>Text::_('COM_DECAROFORMS_AMOUNT'),'placeholder'=>'0,00','required'=>false],\n            ['key'=>'payment_cause','type'=>'text','category'=>'payment','label'=>Text::_('COM_DECAROFORMS_PAYMENT_CAUSE'),'placeholder'=>'','required'=>false],\n            ['key'=>'payment_reference','type'=>'text','category'=>'payment','label'=>Text::_('COM_DECAROFORMS_PAYMENT_REFERENCE'),'placeholder'=>'','required'=>false],\n"
h=h.replace(payment_line,payment_fields,1)
helper.write_text(h)

# Add translations for payment method field and simplify AI label where present.
translations={
'it-IT':{'COM_DECAROFORMS_FIELD_PAYMENT_METHOD':'Metodo di pagamento','COM_DECAROFORMS_CHATGPT_GENERATOR':'Generatore AI'},
'en-GB':{'COM_DECAROFORMS_FIELD_PAYMENT_METHOD':'Payment method','COM_DECAROFORMS_CHATGPT_GENERATOR':'AI generator'},
'fr-FR':{'COM_DECAROFORMS_FIELD_PAYMENT_METHOD':'Mode de paiement','COM_DECAROFORMS_CHATGPT_GENERATOR':'Générateur IA'},
}
for lang,vals in translations.items():
    for p in comp.rglob(f'{lang}.com_decaroforms.ini'):
        s=p.read_text()
        for k,v in vals.items():
            line=f'{k}="{v}"'
            if re.search(rf'^{re.escape(k)}=',s,re.M): s=re.sub(rf'^{re.escape(k)}=.*$',line,s,flags=re.M)
            else:s+='\n'+line
        p.write_text(s)
    for p in comp.rglob('com_decaroforms.ini'):
        if f'/{lang}/' not in str(p).replace('\\','/'): continue
        s=p.read_text()
        for k,v in vals.items():
            line=f'{k}="{v}"'
            if re.search(rf'^{re.escape(k)}=',s,re.M): s=re.sub(rf'^{re.escape(k)}=.*$',line,s,flags=re.M)
            else:s+='\n'+line
        p.write_text(s)

# Bump versions.
for p in [comp/'com_decaroforms.xml',plug/'decaroforms.xml',helper]:
    s=p.read_text()
    if '1.3.1' not in s: raise RuntimeError(f'1.3.1 not found in {p}')
    p.write_text(s.replace('1.3.1','1.3.2'))

builder.write_text(t)
print('Forms 1.3.2 UX patch applied')
