#!/usr/bin/env python3
from pathlib import Path
import re, sys

if len(sys.argv)!=3: raise SystemExit('usage: translations.py COMPONENT_ROOT PLUGIN_ROOT')
comp,plug=map(Path,sys.argv[1:])

common={
'COM_DECAROFORMS_SECTION_SETTINGS':('Impostazioni modulo','Form settings','Paramètres du formulaire'),
'COM_DECAROFORMS_SECTION_TEMPLATES':('Modelli rapidi','Quick templates','Modèles rapides'),
'COM_DECAROFORMS_SECTION_SELECTED':('Campi selezionati','Selected fields','Champs sélectionnés'),
'COM_DECAROFORMS_SECTION_LAYOUT':('Layout campi','Field layout','Mise en page des champs'),
'COM_DECAROFORMS_SECTION_LIBRARY':('Libreria campi','Field library','Bibliothèque de champs'),
'COM_DECAROFORMS_SECTION_SUBMISSIONS':('Gestione invii','Submission management','Gestion des envois'),
'COM_DECAROFORMS_SECTION_EMAIL':('Impostazioni email','Email settings','Paramètres e-mail'),
'COM_DECAROFORMS_SECTION_VALIDATION':('Validazione e conferma','Validation and confirmation','Validation et confirmation'),
'COM_DECAROFORMS_SECTION_CUSTOM_CODE':('Codice personalizzato','Custom code','Code personnalisé'),
'COM_DECAROFORMS_SECTION_INTEGRATIONS':('Integrazioni e automazioni','Integrations and automations','Intégrations et automatisations'),
'COM_DECAROFORMS_SUCCESS_BELOW_NOTE':('Il messaggio viene mostrato sotto il pulsante Invia dopo un invio riuscito.','The message is shown below the Send button after a successful submission.','Le message s’affiche sous le bouton Envoyer après un envoi réussi.'),
'COM_DECAROFORMS_LAYOUT_COLUMNS':('Numero colonne','Number of columns','Nombre de colonnes'),
'COM_DECAROFORMS_LAYOUT_MOBILE_STACK':('Su smartphone disponi i campi al 100%','Stack fields at 100% on smartphones','Empiler les champs à 100 % sur smartphone'),
'COM_DECAROFORMS_LAYOUT_APPLY_FIELDS':('Applica ai campi','Apply to fields','Appliquer aux champs'),
'COM_DECAROFORMS_LAYOUT_NOTE':('Le larghezze della riga devono totalizzare 100%. Su smartphone è consigliata la disposizione a una colonna.','Row widths must total 100%. A single-column layout is recommended on smartphones.','Les largeurs de la ligne doivent totaliser 100 %. Une seule colonne est recommandée sur smartphone.'),
'COM_DECAROFORMS_ROW':('Riga','Row','Ligne'),'COM_DECAROFORMS_COLUMN':('Colonna','Column','Colonne'),'COM_DECAROFORMS_WIDTH':('Larghezza','Width','Largeur'),
'COM_DECAROFORMS_CATEGORY_CHOICES':('Scelte','Choices','Choix'),'COM_DECAROFORMS_CATEGORY_VALUES':('Numeri e valori','Numbers and values','Nombres et valeurs'),'COM_DECAROFORMS_CATEGORY_DATETIME':('Date e ora','Date and time','Date et heure'),'COM_DECAROFORMS_CATEGORY_PAYMENT':('Pagamento','Payment','Paiement'),'COM_DECAROFORMS_CATEGORY_STRUCTURE':('Struttura','Structure','Structure'),
'COM_DECAROFORMS_DEFAULT_VALUE':('Valore predefinito','Default value','Valeur par défaut'),'COM_DECAROFORMS_FIELD_LAYOUT':('Layout del campo','Field layout','Mise en page du champ'),
'COM_DECAROFORMS_CONDITIONS':('Condizioni avanzate','Advanced conditions','Conditions avancées'),'COM_DECAROFORMS_ADD_CONDITION':('Aggiungi condizione','Add condition','Ajouter une condition'),'COM_DECAROFORMS_ALL_CONDITIONS':('Tutte le condizioni','All conditions','Toutes les conditions'),'COM_DECAROFORMS_ANY_CONDITION':('Una qualsiasi condizione','Any condition','Une condition quelconque'),'COM_DECAROFORMS_CONDITION_ACTION':('Azione','Action','Action'),'COM_DECAROFORMS_CONDITION_LOGIC':('Logica','Logic','Logique'),'COM_DECAROFORMS_NO_CONDITIONS':('Nessuna condizione configurata.','No conditions configured.','Aucune condition configurée.'),
'COM_DECAROFORMS_OPTIONS_COMPACT_NOTE':('Una voce per riga. Il campo si espande solo quando serve.','One option per line. The field expands only when needed.','Une option par ligne. Le champ ne s’agrandit que si nécessaire.'),
'COM_DECAROFORMS_TYPE_DATETIME':('Data e ora','Date and time','Date et heure'),'COM_DECAROFORMS_TYPE_MULTISELECT':('Selezione multipla','Multiple select','Sélection multiple'),'COM_DECAROFORMS_TYPE_CHECKBOX':('Checkbox','Checkbox','Case à cocher'),'COM_DECAROFORMS_TYPE_TOGGLE':('Sì / No','Yes / No','Oui / Non'),'COM_DECAROFORMS_TYPE_UPLOAD':('Caricamento file','File upload','Téléversement de fichier'),'COM_DECAROFORMS_TYPE_RANGE':('Range Slider','Range Slider','Curseur de plage'),'COM_DECAROFORMS_TYPE_SEPARATOR':('Separatore / Linea','Separator / Line','Séparateur / Ligne'),'COM_DECAROFORMS_TYPE_PAGEBREAK':('Interruzione pagina','Page break','Saut de page'),'COM_DECAROFORMS_TYPE_MULTIPAGE':('Multipage / Nuova pagina','Multipage / New page','Multipage / Nouvelle page'),'COM_DECAROFORMS_TYPE_HEADING':('Titolo','Heading','Titre'),'COM_DECAROFORMS_TYPE_INFO':('Testo informativo','Information text','Texte informatif'),'COM_DECAROFORMS_TYPE_FIELDSET':('Gruppo / Fieldset','Group / Fieldset','Groupe / Fieldset'),'COM_DECAROFORMS_TYPE_HIDDEN':('Campo nascosto','Hidden field','Champ masqué'),'COM_DECAROFORMS_TYPE_MAP':('Mappa / Posizione','Map / Location','Carte / Position'),'COM_DECAROFORMS_TYPE_PAYMENT':('Pagamento','Payment','Paiement'),'COM_DECAROFORMS_TYPE_CALCULATED':('Campo calcolato','Calculated field','Champ calculé'),
'COM_DECAROFORMS_FIELD_TAX_CODE':('Codice fiscale','Tax code','Code fiscal'),'COM_DECAROFORMS_FIELD_MOBILE':('Cellulare','Mobile phone','Téléphone portable'),'COM_DECAROFORMS_FIELD_PEC':('PEC','Certified email','E-mail certifié'),'COM_DECAROFORMS_FIELD_WEBSITE':('Sito web','Website','Site web'),'COM_DECAROFORMS_FIELD_REGION':('Regione','Region','Région'),'COM_DECAROFORMS_FIELD_MAP':('Mappa / Posizione','Map / Location','Carte / Position'),'COM_DECAROFORMS_FIELD_CERTIFICATE':('Certificato','Certificate','Certificat'),'COM_DECAROFORMS_FIELD_MULTISELECT':('Selezione multipla personalizzata','Custom multiple select','Sélection multiple personnalisée'),'COM_DECAROFORMS_FIELD_CHECKBOX':('Checkbox personalizzata','Custom checkbox','Case à cocher personnalisée'),'COM_DECAROFORMS_FIELD_TOGGLE':('Scelta Sì / No','Yes / No choice','Choix Oui / Non'),'COM_DECAROFORMS_FIELD_RANGE':('Range Slider','Range Slider','Curseur de plage'),'COM_DECAROFORMS_FIELD_TIME':('Ora personalizzata','Custom time','Heure personnalisée'),'COM_DECAROFORMS_FIELD_DATETIME':('Data e ora personalizzate','Custom date and time','Date et heure personnalisées'),'COM_DECAROFORMS_FIELD_CUSTOM_UPLOAD':('Allegato personalizzato','Custom attachment','Pièce jointe personnalisée'),'COM_DECAROFORMS_FIELD_HEADING':('Titolo sezione','Section heading','Titre de section'),'COM_DECAROFORMS_FIELD_INFO':('Testo informativo','Information text','Texte informatif'),'COM_DECAROFORMS_FIELD_SEPARATOR':('Separatore / Linea','Separator / Line','Séparateur / Ligne'),'COM_DECAROFORMS_FIELD_PAGEBREAK':('Interruzione pagina','Page break','Saut de page'),'COM_DECAROFORMS_FIELD_MULTIPAGE':('Multipage / Nuova pagina','Multipage / New page','Multipage / Nouvelle page'),'COM_DECAROFORMS_FIELD_FIELDSET':('Gruppo / Fieldset','Group / Fieldset','Groupe / Fieldset'),'COM_DECAROFORMS_FIELD_HIDDEN':('Campo nascosto','Hidden field','Champ masqué'),'COM_DECAROFORMS_FIELD_CALCULATION':('Calcolo','Calculation','Calcul'),
'COM_DECAROFORMS_ROLE_PRESIDENT':('Presidente','President','Président'),'COM_DECAROFORMS_ROLE_VICEPRESIDENT':('Vicepresidente','Vice president','Vice-président'),'COM_DECAROFORMS_ROLE_SECRETARY':('Segretario','Secretary','Secrétaire'),'COM_DECAROFORMS_ROLE_TREASURER':('Tesoriere','Treasurer','Trésorier'),'COM_DECAROFORMS_ROLE_COUNCILLOR':('Consigliere','Board member','Conseiller'),'COM_DECAROFORMS_ROLE_MANAGER':('Responsabile','Manager','Responsable'),
'COM_DECAROFORMS_ADDRESS_SEARCH_PLACEHOLDER':('Cerca o inserisci un indirizzo','Search or enter an address','Rechercher ou saisir une adresse'),
'COM_DECAROFORMS_UPLOAD_SETTINGS':('Impostazioni allegato','Attachment settings','Paramètres de pièce jointe'),'COM_DECAROFORMS_FILE_TYPES':('Tipi file consentiti','Allowed file types','Types de fichiers autorisés'),'COM_DECAROFORMS_MAX_MB':('Dimensione massima (MB)','Maximum size (MB)','Taille maximale (Mo)'),'COM_DECAROFORMS_MAX_FILES':('Numero massimo file','Maximum number of files','Nombre maximal de fichiers'),'COM_DECAROFORMS_MULTIPLE_FILES':('Consenti più file','Allow multiple files','Autoriser plusieurs fichiers'),'COM_DECAROFORMS_BUTTON_LABEL':('Etichetta pulsante','Button label','Libellé du bouton'),
'COM_DECAROFORMS_RANGE_SETTINGS':('Impostazioni Range Slider','Range Slider settings','Paramètres du curseur'),'COM_DECAROFORMS_UNIT':('Unità','Unit','Unité'),'COM_DECAROFORMS_DUAL_RANGE':('Doppio cursore (intervallo)','Dual handle (range)','Double curseur (intervalle)'),
'COM_DECAROFORMS_LINE_SETTINGS':('Impostazioni linea','Line settings','Paramètres de ligne'),'COM_DECAROFORMS_COLOR':('Colore','Color','Couleur'),'COM_DECAROFORMS_BORDER_WIDTH':('Spessore bordo','Border width','Épaisseur de bordure'),'COM_DECAROFORMS_BORDER_STYLE':('Stile bordo','Border style','Style de bordure'),'COM_DECAROFORMS_LINE_LENGTH':('Larghezza linea','Line width','Largeur de ligne'),'COM_DECAROFORMS_MARGIN':('Margine sopra/sotto','Top/bottom margin','Marge haut/bas'),'COM_DECAROFORMS_SHOW_LINE_FRONTEND':('Mostra linea anche nel frontend','Show line on frontend too','Afficher aussi la ligne côté public'),
'COM_DECAROFORMS_MULTIPAGE_SETTINGS':('Impostazioni pagina','Page settings','Paramètres de page'),'COM_DECAROFORMS_PAGE_TITLE':('Titolo pagina','Page title','Titre de page'),'COM_DECAROFORMS_PAGE_DESCRIPTION':('Descrizione pagina','Page description','Description de page'),'COM_DECAROFORMS_SHOW_PROGRESS':('Mostra avanzamento','Show progress','Afficher la progression'),'COM_DECAROFORMS_PAGE_TITLE_DEFAULT':('Nuova pagina','New page','Nouvelle page'),
'COM_DECAROFORMS_MAP_SETTINGS':('Impostazioni mappa','Map settings','Paramètres de carte'),'COM_DECAROFORMS_ALLOW_GEOLOCATION':('Consenti “Usa la mia posizione”','Allow “Use my location”','Autoriser « Utiliser ma position »'),
'COM_DECAROFORMS_PAYMENT':('Pagamento','Payment','Paiement'),'COM_DECAROFORMS_PAYMENT_SETTINGS':('Impostazioni pagamento','Payment settings','Paramètres de paiement'),'COM_DECAROFORMS_PAYMENT_METHOD':('Metodo','Method','Méthode'),'COM_DECAROFORMS_ACCOUNT_HOLDER':('Intestatario','Account holder','Titulaire'),'COM_DECAROFORMS_AMOUNT':('Importo','Amount','Montant'),'COM_DECAROFORMS_PAYMENT_CAUSE':('Causale','Payment reason','Motif du paiement'),'COM_DECAROFORMS_PAYMENT_REFERENCE':('Riferimento pagamento','Payment reference','Référence de paiement'),'COM_DECAROFORMS_PAYMENT_STATUS':('Stato pagamento','Payment status','Statut du paiement'),'COM_DECAROFORMS_PAYMENT_PENDING':('Da verificare','To verify','À vérifier'),'COM_DECAROFORMS_PAYMENT_VERIFIED':('Verificato','Verified','Vérifié'),'COM_DECAROFORMS_COMING_SOON':('Prossimamente','Coming soon','Bientôt disponible'),
'COM_DECAROFORMS_CALC_SETTINGS':('Impostazioni calcolo','Calculation settings','Paramètres de calcul'),'COM_DECAROFORMS_FORMULA':('Formula','Formula','Formule'),'COM_DECAROFORMS_PREFIX':('Prefisso','Prefix','Préfixe'),'COM_DECAROFORMS_SUFFIX':('Suffisso','Suffix','Suffixe'),'COM_DECAROFORMS_DECIMALS':('Decimali','Decimals','Décimales'),'COM_DECAROFORMS_VISIBLE_FIELD':('Mostra il risultato nel modulo','Show result in the form','Afficher le résultat dans le formulaire'),'COM_DECAROFORMS_CONTENT':('Contenuto','Content','Contenu'),'COM_DECAROFORMS_MIN_LENGTH':('Lunghezza minima','Minimum length','Longueur minimale'),'COM_DECAROFORMS_MAX_LENGTH':('Lunghezza massima','Maximum length','Longueur maximale'),'COM_DECAROFORMS_NUMERIC_ID_NOTE':('Accetta solo cifre e conserva gli zeri iniziali.','Digits only; leading zeroes are preserved.','Chiffres uniquement ; les zéros initiaux sont conservés.'),'COM_DECAROFORMS_POSTCODE_ITALY_NOTE':('Preset Italia: esattamente 5 cifre; gli zeri iniziali vengono conservati.','Italy preset: exactly 5 digits; leading zeroes are preserved.','Préréglage Italie : exactement 5 chiffres ; les zéros initiaux sont conservés.'),
'COM_DECAROFORMS_FORM_STATUSES':('Stati del modulo','Form statuses','Statuts du formulaire'),'COM_DECAROFORMS_FORM_STATUSES_NOTE':('Definisci liberamente gli stati e il relativo colore.','Define statuses and their colors freely.','Définissez librement les statuts et leurs couleurs.'),'COM_DECAROFORMS_TABLE_COLUMNS':('Colonne della tabella','Table columns','Colonnes du tableau'),'COM_DECAROFORMS_TABLE_COLUMNS_NOTE':('Scegli le colonne da mostrare negli invii.','Choose the columns shown in submissions.','Choisissez les colonnes affichées dans les envois.'),'COM_DECAROFORMS_RESET_DEFAULT':('Ripristina predefinite','Reset defaults','Rétablir les valeurs par défaut'),
'COM_DECAROFORMS_INSERT_VARIABLE':('Inserisci variabile','Insert variable','Insérer une variable'),'COM_DECAROFORMS_INSERT':('Inserisci','Insert','Insérer'),'COM_DECAROFORMS_VARIABLE_NOTE':('Le variabili vengono sostituite con i dati dell’invio.','Variables are replaced with submission data.','Les variables sont remplacées par les données de l’envoi.'),
'COM_DECAROFORMS_EMAIL_ADMIN_SECTION':('Email amministrazione','Administration email','E-mail administration'),'COM_DECAROFORMS_ADMIN_EMAIL_INHERIT':('Lascia vuoto per ereditare l’email amministratore globale di Forms; in ultima istanza viene usata l’email globale Joomla.','Leave blank to inherit the global Forms admin email; Joomla global email is the final fallback.','Laissez vide pour hériter de l’e-mail administrateur global de Forms ; l’e-mail global Joomla est le dernier recours.'),'COM_DECAROFORMS_EMAIL_ADMIN_SUBJECT':('Oggetto email amministratore','Administrator email subject','Objet de l’e-mail administrateur'),'COM_DECAROFORMS_FROM_EMAIL':('Email mittente','From email','E-mail expéditeur'),'COM_DECAROFORMS_FROM_NAME':('Nome mittente','From name','Nom de l’expéditeur'),'COM_DECAROFORMS_REPLY_TO_EMAIL':('Reply-To email','Reply-To email','E-mail Reply-To'),'COM_DECAROFORMS_REPLY_TO_NAME':('Reply-To nome','Reply-To name','Nom Reply-To'),'COM_DECAROFORMS_ADVANCED_OPTIONS':('Opzioni avanzate','Advanced options','Options avancées'),'COM_DECAROFORMS_AUTO_EMAIL_MESSAGE':('Genera automaticamente il contenuto','Auto-generate message content','Générer automatiquement le contenu'),'COM_DECAROFORMS_ATTACH_UPLOADS':('Allega i file caricati','Attach uploaded files','Joindre les fichiers téléversés'),
'COM_DECAROFORMS_EMAIL_USER_SECTION':('Email utente','User email','E-mail utilisateur'),'COM_DECAROFORMS_USER_CONFIRMATION_CLEAR':('Invia email di conferma all’utente','Send confirmation email to the user','Envoyer un e-mail de confirmation à l’utilisateur'),'COM_DECAROFORMS_USER_CONFIRMATION_NOTE':('Invia automaticamente una conferma all’indirizzo email inserito nel modulo.','Automatically sends a confirmation to the email address entered in the form.','Envoie automatiquement une confirmation à l’adresse e-mail saisie dans le formulaire.'),'COM_DECAROFORMS_USER_EMAIL_FIELD':('Campo email destinatario','Recipient email field','Champ e-mail destinataire'),'COM_DECAROFORMS_EMAIL_USER_SUBJECT':('Oggetto email utente','User email subject','Objet de l’e-mail utilisateur'),
'COM_DECAROFORMS_ADDITIONAL_EMAILS':('Email aggiuntive','Additional emails','E-mails supplémentaires'),'COM_DECAROFORMS_ADDITIONAL_EMAILS_NOTE':('Aggiungi notifiche facoltative, anche condizionate dai valori del modulo.','Add optional notifications, including conditional ones based on form values.','Ajoutez des notifications facultatives, y compris conditionnelles selon les valeurs du formulaire.'),'COM_DECAROFORMS_NEW_EMAIL':('Nuova email','New email','Nouvel e-mail'),'COM_DECAROFORMS_NO_ADDITIONAL_EMAILS':('Nessuna email aggiuntiva configurata.','No additional emails configured.','Aucun e-mail supplémentaire configuré.'),'COM_DECAROFORMS_EMAIL_INTERNAL_NAME':('Nome interno','Internal name','Nom interne'),'COM_DECAROFORMS_EMAIL_SUBJECT':('Oggetto email','Email subject','Objet de l’e-mail'),'COM_DECAROFORMS_CONDITION':('Condizione di invio','Send condition','Condition d’envoi'),
'COM_DECAROFORMS_TEMPLATE_MODERN':('Moderno','Modern','Moderne'),'COM_DECAROFORMS_TEMPLATE_ELEGANT':('Elegante','Elegant','Élégant'),'COM_DECAROFORMS_TEMPLATE_RECEIPT':('Ricevuta','Receipt','Reçu'),'COM_DECAROFORMS_TEMPLATE_CUSTOM':('Personalizzato','Custom','Personnalisé'),'COM_DECAROFORMS_TEMPLATE_SELECTED':('Selezionato','Selected','Sélectionné'),'COM_DECAROFORMS_PREVIEW':('Anteprima','Preview','Aperçu'),'COM_DECAROFORMS_CUSTOMIZE':('Personalizza','Customize','Personnaliser'),'COM_DECAROFORMS_HTML_FREE':('HTML libero','Free HTML','HTML libre'),'COM_DECAROFORMS_CHATGPT_GENERATOR':('Genera con ChatGPT','Generate with ChatGPT','Générer avec ChatGPT'),'COM_DECAROFORMS_COPY_CHATGPT_PROMPT':('Copia per ChatGPT','Copy for ChatGPT','Copier pour ChatGPT'),'COM_DECAROFORMS_COPIED':('Copiato','Copied','Copié'),
'COM_DECAROFORMS_BASE_TEMPLATE':('Template di base','Base template','Modèle de base'),'COM_DECAROFORMS_RADIUS':('Raggio bordi','Border radius','Rayon des bordures'),'COM_DECAROFORMS_PRIMARY_COLOR':('Colore principale','Primary color','Couleur principale'),'COM_DECAROFORMS_SECONDARY_COLOR':('Colore secondario','Secondary color','Couleur secondaire'),'COM_DECAROFORMS_BACKGROUND_COLOR':('Colore sfondo','Background color','Couleur de fond'),'COM_DECAROFORMS_TEXT_COLOR':('Colore testo','Text color','Couleur du texte'),'COM_DECAROFORMS_BUTTON_COLOR':('Colore pulsante','Button color','Couleur du bouton'),'COM_DECAROFORMS_BORDER_COLOR':('Colore bordo','Border color','Couleur de bordure'),'COM_DECAROFORMS_RESET_COLORS':('Ripristina colori','Reset colors','Rétablir les couleurs'),'COM_DECAROFORMS_HTML_VARIABLE_NOTE':('Inserisci solo HTML email; puoi usare le variabili del modulo. Script ed eventi HTML vengono rimossi.','Enter email HTML only; form variables are supported. Scripts and HTML event handlers are removed.','Saisissez uniquement du HTML d’e-mail ; les variables du formulaire sont prises en charge. Les scripts et événements HTML sont supprimés.'),
'COM_DECAROFORMS_CHATGPT_INSTRUCTIONS':('Istruzioni per ChatGPT','Instructions for ChatGPT','Instructions pour ChatGPT'),'COM_DECAROFORMS_CHATGPT_PLACEHOLDER':('es. Intestazione rossa, riepilogo in tabella, stile istituzionale…','e.g. red header, table summary, institutional style…','ex. en-tête rouge, résumé en tableau, style institutionnel…'),'COM_DECAROFORMS_CHATGPT_HTML_RESULT':('HTML generato','Generated HTML','HTML généré'),'COM_DECAROFORMS_CHATGPT_PASTE_HTML':('Incolla qui l’HTML restituito da ChatGPT.','Paste the HTML returned by ChatGPT here.','Collez ici le HTML renvoyé par ChatGPT.'),
'COM_DECAROFORMS_VALIDATION':('Validazione','Validation','Validation'),'COM_DECAROFORMS_AJAX_VALIDATION':('Validazione immediata prima dell’invio','Immediate validation before submit','Validation immédiate avant envoi'),'COM_DECAROFORMS_SCROLL_ERROR':('Vai automaticamente al primo errore','Automatically go to the first error','Aller automatiquement à la première erreur'),'COM_DECAROFORMS_REQUIRED_MARKER':('Indicatore campi obbligatori','Required field marker','Marqueur des champs obligatoires'),'COM_DECAROFORMS_ERROR_MESSAGE':('Messaggio errore generale','General error message','Message d’erreur général'),'COM_DECAROFORMS_DEFAULT_ERROR_MESSAGE':('Ci sono alcuni campi da correggere. Controlla quelli evidenziati.','Some fields need to be corrected. Check the highlighted fields.','Certains champs doivent être corrigés. Vérifiez les champs signalés.'),
'COM_DECAROFORMS_CONFIRMATION':('Conferma dopo l’invio','Confirmation after submission','Confirmation après envoi'),'COM_DECAROFORMS_SHOW_CONFIRMATION':('Mostra messaggio di conferma','Show confirmation message','Afficher le message de confirmation'),'COM_DECAROFORMS_CONFIRM_POSITION':('Posizione','Position','Position'),'COM_DECAROFORMS_CONFIRM_BELOW':('Sotto il pulsante Invia','Below the Send button','Sous le bouton Envoyer'),'COM_DECAROFORMS_CONFIRM_REPLACE':('Sostituisci il modulo','Replace the form','Remplacer le formulaire'),'COM_DECAROFORMS_CONFIRM_MODAL':('Popup / Modal','Popup / Modal','Popup / Modal'),'COM_DECAROFORMS_SCROLL_CONFIRM':('Scorri automaticamente al messaggio','Automatically scroll to the message','Faire défiler automatiquement jusqu’au message'),'COM_DECAROFORMS_SHOW_CONTINUE':('Mostra pulsante Continua','Show Continue button','Afficher le bouton Continuer'),'COM_DECAROFORMS_CONTINUE_LABEL':('Testo pulsante Continua','Continue button text','Texte du bouton Continuer'),'COM_DECAROFORMS_CONTINUE_URL':('Destinazione Continua','Continue destination','Destination Continuer'),'COM_DECAROFORMS_CONTINUE':('Continua','Continue','Continuer'),
'COM_DECAROFORMS_SECURITY':('Sicurezza invio','Submission security','Sécurité de l’envoi'),'COM_DECAROFORMS_MIN_SECONDS':('Tempo minimo compilazione (secondi)','Minimum completion time (seconds)','Temps minimal de remplissage (secondes)'),'COM_DECAROFORMS_RATE_SECONDS':('Intervallo minimo tra invii (secondi)','Minimum interval between submissions (seconds)','Intervalle minimal entre envois (secondes)'),'COM_DECAROFORMS_SECURITY_NOTE':('CSRF, honeypot e validazione server restano sempre attivi.','CSRF, honeypot and server-side validation always remain active.','CSRF, honeypot et validation côté serveur restent toujours actifs.'),
'COM_DECAROFORMS_CUSTOM_CSS':('CSS personalizzato','Custom CSS','CSS personnalisé'),'COM_DECAROFORMS_CUSTOM_JS':('JavaScript personalizzato','Custom JavaScript','JavaScript personnalisé'),'COM_DECAROFORMS_CUSTOM_CSS_NOTE':('Inserisci solo dichiarazioni CSS, senza tag <style>. Il codice è limitato al wrapper del modulo.','Enter CSS declarations only, without <style> tags. Code is scoped to the form wrapper.','Saisissez uniquement les règles CSS, sans balises <style>. Le code est limité au conteneur du formulaire.'),'COM_DECAROFORMS_CUSTOM_JS_NOTE':('Inserisci JavaScript senza tag <script>. Sono disponibili formElement, formId e form.','Enter JavaScript without <script> tags. formElement, formId and form are available.','Saisissez du JavaScript sans balises <script>. formElement, formId et form sont disponibles.'),'COM_DECAROFORMS_CUSTOM_CODE_WARNING':('Codice errato può modificare o bloccare il comportamento del modulo. Usalo solo se sai cosa stai facendo.','Invalid code can change or break form behaviour. Use it only if you know what you are doing.','Un code incorrect peut modifier ou bloquer le formulaire. Utilisez-le uniquement si vous savez ce que vous faites.'),'COM_DECAROFORMS_CUSTOM_CODE_SUPERUSER':('CSS e JavaScript personalizzati sono disponibili solo ai Super User.','Custom CSS and JavaScript are available to Super Users only.','Le CSS et JavaScript personnalisés sont réservés aux Super Users.'),
'COM_DECAROFORMS_CALCULATIONS':('Calcoli','Calculations','Calculs'),'COM_DECAROFORMS_CALCULATIONS_NOTE':('Crea campi calcolati con formule come {participants} * 25. Il risultato si aggiorna mentre l’utente compila.','Create calculated fields with formulas such as {participants} * 25. The result updates while the user fills in the form.','Créez des champs calculés avec des formules comme {participants} * 25. Le résultat se met à jour pendant la saisie.'),'COM_DECAROFORMS_ADD_CALCULATED_FIELD':('Aggiungi campo calcolato','Add calculated field','Ajouter un champ calculé'),
'COM_DECAROFORMS_SHEETS_ENABLE':('Invia automaticamente gli invii a Google Sheets','Automatically send submissions to Google Sheets','Envoyer automatiquement les envois vers Google Sheets'),'COM_DECAROFORMS_SHEETS_WEBHOOK':('URL Webhook Google Apps Script','Google Apps Script webhook URL','URL Webhook Google Apps Script'),'COM_DECAROFORMS_SHEETS_WEBHOOK_NOTE':('Usa un Web App Apps Script HTTPS. Forms salva sempre prima l’invio nel database Joomla.','Use an HTTPS Apps Script Web App. Forms always saves the submission to Joomla first.','Utilisez une Web App Apps Script HTTPS. Forms enregistre toujours d’abord l’envoi dans Joomla.'),'COM_DECAROFORMS_SHEETS_SECRET':('Segreto webhook facoltativo','Optional webhook secret','Secret webhook facultatif'),'COM_DECAROFORMS_SHEETS_INCLUDE_FILES':('Invia metadati degli allegati','Send attachment metadata','Envoyer les métadonnées des pièces jointes'),'COM_DECAROFORMS_SHEETS_PRIMARY_DB':('Il database di Forms rimane la fonte principale: un errore Google Sheets non annulla l’invio.','The Forms database remains the source of truth: a Google Sheets error does not cancel the submission.','La base Forms reste la source principale : une erreur Google Sheets n’annule pas l’envoi.'),
'COM_DECAROFORMS_CONFIG_FROM_EMAIL':('Email mittente predefinita','Default sender email','E-mail expéditeur par défaut'),'COM_DECAROFORMS_CONFIG_FROM_EMAIL_DESC':('Lascia vuoto per usare Mail From globale di Joomla.','Leave blank to use Joomla global Mail From.','Laissez vide pour utiliser le Mail From global de Joomla.'),'COM_DECAROFORMS_CONFIG_FROM_NAME':('Nome mittente predefinito','Default sender name','Nom d’expéditeur par défaut'),'COM_DECAROFORMS_CONFIG_FROM_NAME_DESC':('Lascia vuoto per usare From Name globale di Joomla.','Leave blank to use Joomla global From Name.','Laissez vide pour utiliser le From Name global de Joomla.'),'COM_DECAROFORMS_CONFIG_REPLY_EMAIL':('Reply-To predefinito','Default Reply-To','Reply-To par défaut'),'COM_DECAROFORMS_CONFIG_REPLY_EMAIL_DESC':('Reply-To facoltativo ereditabile dai moduli.','Optional Reply-To inherited by forms.','Reply-To facultatif héritable par les formulaires.'),'COM_DECAROFORMS_CONFIG_REPLY_NAME':('Nome Reply-To predefinito','Default Reply-To name','Nom Reply-To par défaut'),'COM_DECAROFORMS_CONFIG_REPLY_NAME_DESC':('Nome facoltativo associato al Reply-To predefinito.','Optional name associated with the default Reply-To.','Nom facultatif associé au Reply-To par défaut.'),
'COM_DECAROFORMS_CLOSE':('Chiudi','Close','Fermer')
}

plugin_keys={
'PLG_SYSTEM_DECAROFORMS_PREVIOUS':('Indietro','Previous','Précédent'),'PLG_SYSTEM_DECAROFORMS_NEXT':('Avanti','Next','Suivant'),'PLG_SYSTEM_DECAROFORMS_CONTINUE':('Continua','Continue','Continuer'),'PLG_SYSTEM_DECAROFORMS_UPLOAD_HELP':('Formati: %s · massimo %d MB per file.','Formats: %s · maximum %d MB per file.','Formats : %s · maximum %d Mo par fichier.'),'PLG_SYSTEM_DECAROFORMS_TOO_MANY_FILES':('Puoi caricare al massimo %d file.','You can upload at most %d files.','Vous pouvez téléverser au maximum %d fichiers.'),'PLG_SYSTEM_DECAROFORMS_USE_LOCATION':('Usa la mia posizione','Use my location','Utiliser ma position'),'PLG_SYSTEM_DECAROFORMS_BANK_TRANSFER':('Pagamento via bonifico','Bank transfer payment','Paiement par virement'),'PLG_SYSTEM_DECAROFORMS_HOLDER':('Intestatario','Account holder','Titulaire'),'PLG_SYSTEM_DECAROFORMS_AMOUNT':('Importo','Amount','Montant'),'PLG_SYSTEM_DECAROFORMS_COMING_SOON':('Prossimamente','Coming soon','Bientôt disponible'),'PLG_SYSTEM_DECAROFORMS_INVALID_POSTCODE':('Inserisci un CAP valido di 5 cifre.','Enter a valid 5-digit Italian postcode.','Saisissez un code postal italien valide de 5 chiffres.'),'PLG_SYSTEM_DECAROFORMS_INVALID_MEMBER_NUMBER':('Inserisci un numero socio valido composto solo da cifre.','Enter a valid membership number containing digits only.','Saisissez un numéro de membre valide composé uniquement de chiffres.')
}

def quote(v): return v.replace('\\','\\\\').replace('"','\\"')
def upsert(path,key,value):
    text=path.read_text() if path.exists() else ''
    line=f'{key}="{quote(value)}"'
    pat=re.compile(r'^'+re.escape(key)+r'=.*$',re.M)
    if pat.search(text): text=pat.sub(line,text,count=1)
    else: text=text.rstrip()+('\n' if text.strip() else '')+line+'\n'
    path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text)

tags=['it-IT','en-GB','fr-FR']
for idx,tag in enumerate(tags):
    for base in [comp/f'administrator/components/com_decaroforms/language/{tag}/com_decaroforms.ini',comp/f'site/components/com_decaroforms/language/{tag}/com_decaroforms.ini']:
        if base.exists():
            for k,vals in common.items(): upsert(base,k,vals[idx])
    pp=plug/f'language/{tag}/plg_system_decaroforms.ini'
    for k,vals in plugin_keys.items(): upsert(pp,k,vals[idx])
print('Forms 1.3.0 translations updated')
