<?php

defined('_JEXEC') or die;
use DeCaro\Component\Forms\Administrator\Helper\FormHelper;
use DeCaro\Component\Forms\Administrator\Helper\ImportHelper;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
?>
<style>
.df-imp{--df:#e60046;max-width:none;}.df-head{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;margin:4px 0 18px}.df-head h2{margin:0;font-size:27px}.df-head p{margin:5px 0 0;color:var(--bs-secondary-color,#667085)}.df-actions{display:flex;gap:8px;flex-wrap:wrap}.df-btn{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 14px;border:1px solid var(--bs-border-color,#d9dee5);border-radius:6px;background:var(--bs-body-bg,#fff);color:inherit!important;text-decoration:none;font-weight:750}.df-primary{background:var(--df);border-color:var(--df);color:#fff!important}.df-card{margin-bottom:14px;border:1px solid var(--bs-border-color,#dfe3e7);border-radius:8px;background:var(--bs-body-bg,#fff);overflow:hidden}.df-card h3{margin:0;padding:14px 16px;background:var(--bs-tertiary-bg,#f7f8fa);border-bottom:1px solid var(--bs-border-color,#dfe3e7);font-size:18px}.df-body{padding:16px}.df-sources{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.df-source{border:1px solid var(--bs-border-color,#d9dee5);border-radius:8px;padding:14px}.df-source h4{margin:0 0 5px;font-size:17px}.df-source p{margin:0 0 12px;color:var(--bs-secondary-color,#667085);font-size:13px}.df-field{margin-bottom:12px}.df-field label{display:block;font-weight:700;margin-bottom:5px}.df-field input,.df-field select{width:100%;min-height:41px;border:1px solid var(--bs-border-color,#d9dee5);border-radius:6px;background:var(--bs-body-bg,#fff);color:inherit;padding:0 10px}.df-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.df-note{padding:12px 14px;border-left:4px solid var(--df);background:var(--bs-tertiary-bg,#f7f8fa);border-radius:4px}.df-muted{color:var(--bs-secondary-color,#667085);font-size:12px}.df-tablewrap{overflow:auto}.df-table{width:100%;border-collapse:collapse;min-width:760px}.df-table th,.df-table td{padding:9px 10px;border-bottom:1px solid var(--bs-border-color,#e7eaee);text-align:left;vertical-align:top}.df-table th{font-size:11px;text-transform:uppercase;color:var(--bs-secondary-color,#667085)}.df-map select{min-width:210px;min-height:36px}.df-pill{display:inline-flex;padding:4px 8px;border-radius:999px;background:#e8f7ee;color:#176b3a;font-size:12px;font-weight:800}.df-danger{background:#fdebec;color:#9f2430}.df-radio{display:flex;gap:8px;align-items:flex-start;margin:7px 0}.df-source-fields{display:none;margin-top:10px}.df-source-fields.active{display:block}.df-preview td{max-width:240px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.df-submitbar{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:16px}.df-checkline{display:flex;gap:8px;align-items:center}.df-checkline input{width:18px;height:18px}@media(max-width:760px){.df-head{flex-direction:column;align-items:flex-start}.df-sources,.df-grid{grid-template-columns:1fr}.df-actions{width:100%}.df-btn{flex:1}.df-submitbar{flex-direction:column;align-items:stretch}}
</style>
<div class="df-imp">
<div class="df-head"><div><h2><?php echo Text::_('COM_DECAROFORMS_IMPORT_TITLE'); ?></h2><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_DESC'); ?></p></div><div class="df-actions"><a class="df-btn" href="<?php echo $this->formsUrl; ?>"><?php echo Text::_('COM_DECAROFORMS_MENU_FORMS'); ?></a><a class="df-btn" href="<?php echo $this->informationUrl; ?>"><?php echo Text::_('COM_DECAROFORMS_INFORMATION'); ?></a></div></div>

<?php if($this->stage==='source'): ?>
<form method="post" enctype="multipart/form-data" action="<?php echo $this->prepareUrl; ?>">
<section class="df-card"><h3><?php echo Text::_('COM_DECAROFORMS_IMPORT_TARGET'); ?></h3><div class="df-body"><div class="df-field"><label for="target_form_id"><?php echo Text::_('COM_DECAROFORMS_IMPORT_TARGET_LABEL'); ?></label><select id="target_form_id" name="target_form_id"><option value="0"><?php echo Text::_('COM_DECAROFORMS_IMPORT_NEW_FORM'); ?></option><?php foreach($this->forms as $f): ?><option value="<?php echo (int)$f['id']; ?>"><?php echo $e($f['title']); ?> (#<?php echo (int)$f['id']; ?>)</option><?php endforeach; ?></select><div class="df-muted"><?php echo Text::_('COM_DECAROFORMS_IMPORT_TARGET_HELP'); ?></div></div></div></section>
<section class="df-card"><h3><?php echo Text::_('COM_DECAROFORMS_IMPORT_SOURCE'); ?></h3><div class="df-body"><div class="df-sources">
<div class="df-source"><label class="df-radio"><input type="radio" name="source_type" value="joomla_db" checked><strong><?php echo Text::_('COM_DECAROFORMS_IMPORT_JOOMLA_DB'); ?></strong></label><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_JOOMLA_DB_DESC'); ?></p><div class="df-source-fields active" data-source="joomla_db"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_TABLE'); ?></label><select name="joomla_table"><?php foreach($this->tables as $t): ?><option value="<?php echo $e($t['value']); ?>"><?php echo $e($t['label']); ?></option><?php endforeach; ?></select></div></div></div>
<div class="df-source"><label class="df-radio"><input type="radio" name="source_type" value="csv"><strong><?php echo Text::_('COM_DECAROFORMS_IMPORT_CSV'); ?></strong></label><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_CSV_DESC'); ?></p><div class="df-source-fields" data-source="csv"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_FILE'); ?></label><input type="file" name="csv_file" accept=".csv,.txt,.tsv,text/csv,text/plain"></div></div></div>
<div class="df-source"><label class="df-radio"><input type="radio" name="source_type" value="google_sheets"><strong>Google Sheets</strong></label><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_SHEETS_DESC'); ?></p><div class="df-source-fields" data-source="google_sheets"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_SHEET_URL'); ?></label><input type="url" name="google_url" placeholder="https://docs.google.com/spreadsheets/d/..."></div></div></div>
<div class="df-source"><label class="df-radio"><input type="radio" name="source_type" value="google_forms"><strong>Google Forms</strong></label><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_FORMS_DESC'); ?></p><div class="df-source-fields" data-source="google_forms"><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_RESPONSE_SHEET_URL'); ?></label><input type="url" name="google_url" placeholder="https://docs.google.com/spreadsheets/d/..."></div></div></div>
<div class="df-source"><label class="df-radio"><input type="radio" name="source_type" value="external_db"><strong>MySQL / MariaDB</strong></label><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_EXTERNAL_DESC'); ?></p><div class="df-source-fields" data-source="external_db"><div class="df-grid"><div class="df-field"><label>Host</label><input name="ext_host"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_PORT'); ?></label><input type="number" name="ext_port" value="3306"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_DATABASE'); ?></label><input name="ext_database"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_TABLE'); ?></label><input name="ext_table"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_USERNAME'); ?></label><input name="ext_username" autocomplete="off"></div><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_PASSWORD'); ?></label><input type="password" name="ext_password" autocomplete="new-password"></div></div><div class="df-muted"><?php echo Text::_('COM_DECAROFORMS_IMPORT_EXTERNAL_SECURITY'); ?></div></div></div>
<div class="df-source"><h4><?php echo Text::_('COM_DECAROFORMS_IMPORT_LSFS_PRESET'); ?></h4><p><?php echo Text::_('COM_DECAROFORMS_IMPORT_LSFS_DESC'); ?></p><?php if($this->lsfs['installed']): ?><span class="df-pill"><?php echo Text::_('COM_DECAROFORMS_LSFS_DETECTED'); ?></span> <a class="df-btn" style="margin-top:10px" href="<?php echo $this->lsfsUrl; ?>"><?php echo Text::_('COM_DECAROFORMS_IMPORT_OPEN_PRESET'); ?></a><?php else: ?><span class="df-pill df-danger"><?php echo Text::_('COM_DECAROFORMS_LSFS_NOT_DETECTED'); ?></span><?php endif; ?></div>
</div><div class="df-submitbar"><span class="df-muted"><?php echo Text::_('COM_DECAROFORMS_IMPORT_PUBLIC_SHEETS_NOTE'); ?></span><button type="submit" class="df-btn df-primary"><?php echo Text::_('COM_DECAROFORMS_IMPORT_ANALYZE'); ?></button></div></div></section><?php echo HTMLHelper::_('form.token'); ?></form>
<script>(()=>{const radios=[...document.querySelectorAll('input[name="source_type"]')],panels=[...document.querySelectorAll('.df-source-fields')];const draw=()=>{const v=radios.find(r=>r.checked)?.value;panels.forEach(p=>p.classList.toggle('active',p.dataset.source===v));};radios.forEach(r=>r.addEventListener('change',draw));draw();})();</script>
<?php else: $s=$this->state;$cols=(array)$s['columns'];$target=(int)$s['target_form_id']; ?>
<section class="df-card"><h3><?php echo Text::_('COM_DECAROFORMS_IMPORT_SOURCE_READY_TITLE'); ?></h3><div class="df-body"><span class="df-pill"><?php echo $e($s['source_name']); ?></span> <strong><?php echo (int)$s['count']; ?></strong> <?php echo Text::_('COM_DECAROFORMS_RECORDS'); ?><p class="df-muted"><?php echo Text::_('COM_DECAROFORMS_IMPORT_SOURCE_READY_HELP'); ?></p></div></section>
<section class="df-card"><h3><?php echo Text::_('COM_DECAROFORMS_IMPORT_PREVIEW'); ?></h3><div class="df-body df-tablewrap"><table class="df-table df-preview"><thead><tr><?php foreach($cols as $c): ?><th><?php echo $e($c); ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach((array)$s['sample'] as $row): ?><tr><?php foreach($cols as $c): ?><td title="<?php echo $e($row[$c]??''); ?>"><?php echo $e(is_array($row[$c]??null)?json_encode($row[$c],JSON_UNESCAPED_UNICODE):($row[$c]??'')); ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></section>
<form method="post" action="<?php echo $this->runUrl; ?>">
<section class="df-card"><h3><?php echo Text::_('COM_DECAROFORMS_IMPORT_MAPPING'); ?></h3><div class="df-body">
<?php if($target<=0): ?><div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_NEW_FORM_TITLE'); ?></label><input name="new_form_title" required placeholder="<?php echo $e(Text::_('COM_DECAROFORMS_IMPORT_NEW_FORM_PLACEHOLDER')); ?>"></div><p class="df-note"><?php echo Text::_('COM_DECAROFORMS_IMPORT_NEW_FORM_HELP'); ?></p><div class="df-tablewrap"><table class="df-table"><thead><tr><th><?php echo Text::_('COM_DECAROFORMS_IMPORT_INCLUDE'); ?></th><th><?php echo Text::_('COM_DECAROFORMS_IMPORT_SOURCE_COLUMN'); ?></th><th><?php echo Text::_('COM_DECAROFORMS_IMPORT_DETECTED_TYPE'); ?></th></tr></thead><tbody><?php foreach($cols as $c): ?><tr><td><label class="df-checkline"><input type="checkbox" name="include[]" value="<?php echo $e($c); ?>" checked></label></td><td><strong><?php echo $e($c); ?></strong></td><td><?php echo $e('auto'); ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php else: ?><p class="df-note"><?php echo Text::_('COM_DECAROFORMS_IMPORT_EXISTING_HELP'); ?></p><div class="df-tablewrap"><table class="df-table df-map"><thead><tr><th><?php echo Text::_('COM_DECAROFORMS_IMPORT_SOURCE_COLUMN'); ?></th><th><?php echo Text::_('COM_DECAROFORMS_IMPORT_TARGET_FIELD'); ?></th></tr></thead><tbody><?php foreach($cols as $c): ?><tr><td><strong><?php echo $e($c); ?></strong></td><td><select name="map[<?php echo $e($c); ?>]"><option value=""><?php echo Text::_('COM_DECAROFORMS_IMPORT_SKIP'); ?></option><?php foreach($this->targetFields as $f): ?><option value="<?php echo $e($f['field_key']); ?>"><?php echo $e($f['label']); ?> (<?php echo $e($f['field_key']); ?>)</option><?php endforeach; ?></select></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</div></section>
<section class="df-card"><h3><?php echo Text::_('COM_DECAROFORMS_IMPORT_METADATA'); ?></h3><div class="df-body"><div class="df-grid">
<?php $selectors=['email'=>Text::_('COM_DECAROFORMS_EMAIL'),'reference'=>Text::_('COM_DECAROFORMS_REFERENCE'),'status'=>Text::_('COM_DECAROFORMS_STATUS'),'date'=>Text::_('COM_DECAROFORMS_DATE'),'note'=>Text::_('COM_DECAROFORMS_INTERNAL_NOTE')];foreach($selectors as $key=>$label): ?><div class="df-field"><label><?php echo $e($label); ?></label><select name="<?php echo $key; ?>_column"><option value=""><?php echo Text::_('COM_DECAROFORMS_IMPORT_NONE'); ?></option><?php foreach($cols as $c): ?><option value="<?php echo $e($c); ?>" <?php echo ($this->auto[$key]??'')===$c?'selected':''; ?>><?php echo $e($c); ?></option><?php endforeach; ?></select></div><?php endforeach; ?>
<div class="df-field"><label><?php echo Text::_('COM_DECAROFORMS_IMPORT_MAX_ROWS'); ?></label><input type="number" min="1" max="<?php echo ImportHelper::MAX_ROWS; ?>" name="limit" value="<?php echo min(ImportHelper::MAX_ROWS,max(1,(int)$s['count'])); ?>"><div class="df-muted"><?php echo Text::sprintf('COM_DECAROFORMS_IMPORT_MAX_ROWS_HELP',ImportHelper::MAX_ROWS); ?></div></div>
</div></div></section>
<div class="df-submitbar"><button class="df-btn" type="submit" form="df-reset"><?php echo Text::_('COM_DECAROFORMS_IMPORT_CHANGE_SOURCE'); ?></button><button class="df-btn df-primary" type="submit" onclick="return confirm(<?php echo $e(json_encode(Text::_('COM_DECAROFORMS_IMPORT_CONFIRM'))); ?>)"><?php echo Text::_('COM_DECAROFORMS_IMPORT_RUN'); ?></button></div><?php echo HTMLHelper::_('form.token'); ?></form>
<form id="df-reset" method="post" action="<?php echo $this->resetUrl; ?>"><?php echo HTMLHelper::_('form.token'); ?></form>
<?php endif; ?>
<?php echo FormHelper::footer(); ?>
</div>
